### ISSUE TITLE
Checkpoint of lonas-llama-7b-commonsense is not Available

### ISSUE THREAD

**Issue by pprp** [IntelLabs/Hardware-Aware-Automated-Machine-Learning#10]
Kindly remind you that [lonas-llama-7b-commonsense](https://huggingface.co/IntelLabs/lonas-llama-7b-commonsense) is not available on huggingface.

**Comment by jpablomch** [comment]
Thank you, Peyton (@pprp ), for your kind reminder and interest in LoNAS!  Please find the adapter checkpoint for LoNAS Llama-7B-commonsense at: [lonas-llama-7b-commonsense-adapter](https://huggingface.co/IntelLabs/lonas-llama-7b-commonsense-adapter)
Please reach out if you have more questions. BTW, if you want to generate and fine-tune the super-network yourself, you can use [this script](https://github.com/IntelLabs/Hardware-Aware-Automated-Machine-Learning/blob/181d06d3d4fb66ed684d331e03862ca80508e107/LoNAS/running_commands#L6).

**Comment by pprp** [comment]
@jpablomch Really appreciate your swift reply!! Thank you for providing the link.
